create table invoice
(
id bigint generated by default as identity,
billing_header_id bigint unique,
primary key (id)
);

create table billing_header
(
id bigint generated by default as identity,
total_invoice_amount numeric(38,2),
billing_id varchar(255),
primary key (id)
);

create table billing_line_information
(
id bigint generated by default as identity,
invoice_id bigint,
line_type varchar(255),
product_type varchar(255),
primary key (id)
);


alter table if exists invoice add constraint FK7inetdesv535rufp5j1viuu0c foreign key (billing_header_id) references billing_header;
alter table if exists billing_line_information add constraint FKtfqr2nedjw73vavqj62tjnpag foreign key (invoice_id) references invoice;
